services:
  - type: web
    name: ruletka
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    autoDeployTrigger: commit
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /health
